### ISSUE TITLE
HexDummy 1.20.1 Yarn mappings should use hexcasting fabric jar in Common subproject

### ISSUE THREAD

**Issue by Master-Bw3** [object-Object/hexdummy#4]
When generating a project for 1.20.1 with Yarn mappings, the `Common` subproject has `modApi(libs.hexcasting.common)` listed in the dependencies section of `build.gradle.kts`. Since the Common jar isn't remapped by loom, this dependency should be changed to `modApi(libs.hexcasting.fabric)` (which includes the Common code).

**Comment by object-Object** [comment]
Thanks!
